steps:

#this step is to deploy the elk to gke using helm
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Authenticate with the Kubernetes cluster
      gcloud container clusters get-credentials ameen-test-cluster --zone us-west1-a --project peerless-column-407106      

      # Install Helm
      curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      chmod +x get_helm.sh
      ./get_helm.sh

      # create namespace for elk 
      kubectl create ns elk
      
      # add ell repo to helm
      helm repo add elastic https://helm.elastic.co
      helm repo update

      # install elk with helm

      helm -n elk upgrade --install elk-elasticsearch elastic/elasticsearch -f values-Elastic.yaml --timeout 5m
      helm -n elk upgrade --install elk-logstash elastic/logstash -f values-Logstash.yaml 
      helm -n elk upgrade --install elk-filebeat elastic/filebeat -f values-FileBeat.yaml
      helm -n elk upgrade --install elasticapm elastic/apm-server -f values-Apm.yaml
      
      helm -n elk upgrade --install elk-kibana elastic/kibana -f values-Kibana.yaml --timeout 5m

      kubectl get secrets --namespace=elk elasticsearch-master-credentials -ojsonpath='{.data.password}' | base64 -d
      kubectl get secrets --namespace=elk elasticsearch-master-credentials -ojsonpath='{.data.username}' | base64 -d
