apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elk-role-binding
  namespace: elk
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: elk
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-binding
  namespace: elk
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: 541847188117@cloudbuild.gserviceaccount.com
  namespace: elk
  apiGroup: rbac.authorization.k8s.io